### ISSUE TITLE
「未踏ジュニアって？」の修正案

### ISSUE THREAD

**Issue by Reputeless** [ukkari/mitoujr#13]
### メンタリングの提供

旧:
PMやその他未踏OBOGを中心とした各界で活躍するPMや、その他専門家による指導が受けられます。

新:
担当のプロジェクトマネージャ（PM）をはじめ、未踏卒業生らを中心とする各界で活躍するエンジニア・専門家の指導が受けられます。

### 未踏事業への推薦

旧:
未踏ジュニアスーパークリエータに認定され、担当PMに承認された場合は2019年度の未踏事業への推薦を受けることができます。

新:
未踏ジュニアスーパークリエータに認定されると、翌年度以降にIPA未踏事業へ応募する際、条件付きで一次選考が免除されます。

**Comment by yasulab** [comment]
PRed. ✅ https://github.com/ukkari/mitoujr/pull/16
